title: Site

tabs:
    content:
        label:
            en: Content
            el: Περιεχόμενο
        icon: text
        columns:
          - width: 2/3
            sections:
                homepage:
                    headline: Home
                    type: pages
                    status: all
                    templates: home
                    max: 1
                categories:
                    headline: Project Categories
                    type: pages
                    status: all
                    templates: category
                    parent: site.find("projects")
                allpages:
                    headline: Pages
                    type: pages
                    status: all
                    templates:
                      - default
                      - about
          - width: 1/3
            sections:
                pagefiles:
                    extends: sections/pagefiles
                siteseo:
                    type: fields
                    fields:
                        logoimage:
                            type: files
                            layout: cards
                            multiple: false
                            label: Logo
                        footerimages:
                            type: files
                            layout: cards
                            label: ISO
                        sitetwitter:
                            type: text
                            label: Site Twitter Username
                        facebook:
                            type: url
                            label: Facebook Page
                        twitter:
                            type: url
                            label: Site Twitter Page
                        instagram:
                            type: url
                            label: Instagram Page
                        pinterest:
                            type: url
                            label: Pinterest Page
                        linkedin:
                            type: url
                            label: LinkedIn Page
